### ISSUE TITLE
> ngrok authtoken 1iC3B9rvJ5z83mZVS6wg9oKGWmB_EzGaWeJ5PPSMidynxdLt

### ISSUE THREAD

**Issue by Fernandobazan2233** [naiyan-official/RDP#4]
> ngrok authtoken 1iC3B9rvJ5z83mZVS6wg9oKGWmB_EzGaWeJ5PPSMidynxdLt

_Originally posted by @Fernandobazan2233 in https://github.com/naiyan-official/RDP/issues/3#issuecomment-830769724_

**Comment by naiyan-official** [comment]
No need ngrok,,,,  just need wibdow powershell code🙂

**Comment by H4CK3REMJ** [comment]
:)

**Comment by naiyan-official** [comment]
মিয়া এইসব উলটা পালটা কাজ বন্ধ করেন😑

**Comment by Mrps6ch0** [comment]
Ki korlam vai?
